name: CI

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'readme/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'readme/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install required packages for puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm install, bundle, and test
        run: |
          npm install
          npm run clean:bundles
          npm run bundle
          npm test
        env:
          CI: true
